version: '3.8'

services:
  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web:latest
    container_name: drug-chat
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BASE_URL=https://api.openai.com
      - CODE=drug-chat-2024
      - HIDE_USER_API_KEY=true
      - CUSTOM_MODELS=gpt-3.5-turbo,gpt-4
      - DEFAULT_MODEL=gpt-3.5-turbo
    restart: unless-stopped
